name: Pylint

on: [push]

jobs:
  sast_scan: 
    name: run Bandiit Scan 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifacts
      run: actions/uploadartifact@v3
      if: always()
      with:
       name: bandit findings
       path: bandit-report.json

     image_scan:
       name: Build Image and Run Image Scan
       runs-on: ubuntu-latest

      steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Setup Docker
        uses:  uses: docker-practice/actions-setup-docker@v1
        with:
          docker_version: '20.10.7'

     - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name:  Build Docekr Image
#       run: docker build -f Dockerfile -t myapp:latest .

#      - name: Docker scout scan
#         uses: docker/scout-action@v1.0.9
#         with: 
#           dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
#           dockerhub-password: ${{ secrets.DOCKER_PWD }}
#           command: quickview,cves
